;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname |2|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.


(define (fibonacci a b sofar)
  (cond [( < (+ a b) 4000000)
  (fibonacci b (+ a b)(cons (+ a b) sofar))]
        [else (reverse sofar)]))

(define evenlist (filter (lambda (x) (= (modulo x 2) 0))
        (fibonacci 1 2 (list 2 1))))

(foldr (lambda (x y) (+ x y)) 0 evenlist)

;; Answer: 4613732